### ISSUE TITLE
can I display youtube videos ?

### ISSUE THREAD

**Issue by hishambakr** [waynell/VideoListPlayer#1]
Many thanks for great work. can I display youtube videos ?

**Comment by waynell** [comment]
Yes, but you should convert it to MP4 link

**Comment by sungerk** [comment]
@hisham2007   you can see the demo from [https://github.com/google/ExoPlayer](ExoPlayer)

**Comment by hishambakr** [comment]
could you give me more details. I have a news reader  which get news from rss which sometimes have youtube links. how to convert youtube links to mp4 on the fly?
