### ISSUE TITLE
NullPointerException onScroll

### ISSUE THREAD

**Issue by Prosanto** [waynell/VideoListPlayer#10]
FATAL EXCEPTION: main
 Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
com.waynell.videolist.visibility.calculator.SingleListViewItemActiveCalculator.findPreviousItem(SingleListViewItemActiveCalculator.java:132)
SingleListViewItemActiveCalculator.calculateActiveItem(SingleListViewItemActiveCalculator.java:301)                                                             SingleListViewItemActiveCalculator.onStateTouchScroll(SingleListViewItemActiveCalculator.java:75)                                                               BaseItemsVisibilityCalculator.onScrolled(BaseItemsVisibilityCalculator.java:43)

**Comment by waynell** [comment]
It has been fixed in latest version
