### ISSUE TITLE
视频加载略缓慢  video loading speed is slow compared with normal videoview in list

### ISSUE THREAD

**Issue by moxiaohu** [waynell/VideoListPlayer#11]
第一次加载视频的时候，尽管网络状况很好,加载速度还是比较慢 。和用videoview 在 list 里面 直接加载相比，速度慢很多。

**Comment by waynell** [comment]
这里使用的加载和VideoView的加载是不一样的。这里是将整个视频文件下载完成之后才开始播放，而videoview是使用的网络流播放并没有等整个视频文件下载完。videoview的弊端在于没有本地缓存
