### ISSUE TITLE
列表播放时,按home键,再打开,控件会黑屏

### ISSUE THREAD

**Issue by 9468lgy** [waynell/VideoListPlayer#15]

**Comment by waynell** [comment]
在OnResume时调一下calculator.onStateLost() 和 calculator.onScrolled(RecyclerView.SCROLL_STATE_IDLE);

**Comment by 9468lgy** [comment]
我在项目里用的时候,这样就不黑屏了,没有在你的项目中尝试,你的项目帮了很大忙,非常感谢~~
 @Override
    public void onSurfaceTextureAvailable(SurfaceTexture arg0, int arg1, int arg2) {
        surface = new Surface(arg0);
        if (mediaPlayer != null) {
            mediaPlayer.setSurface(surface); //当重新可见的时候赋值给mediaPlayer   就不黑屏了
        }
    }
