### ISSUE TITLE
大神，能不能把你之前的那个android 冷启动的demo也传上来额

### ISSUE THREAD

**Issue by i91h1r** [waynell/VideoListPlayer#21]
我这边装制作.9图的环境始终装不上，现在需要一个没有tablayout的.9背景图额，能不能那个项目也传上来额？或者能不能把那个没有tablayout的.9 图发给我额，谢谢啦。。。

**Comment by waynell** [comment]
已看到你在博客中的留言，我们在那边说。
请不要在repo中发起不相关的issue, 谢谢。
