### ISSUE TITLE
上下滑动后VideoView不可见

### ISSUE THREAD

**Issue by Chen-Sir** [waynell/VideoListPlayer#23]
@Override
    public void videoBeginning() {
        mVideoView.setVisibility(View.VISIBLE);
        mPlaybackImage.setVisibility(View.INVISIBLE);
        cancelAlphaAnimate(mVideoCoverImage);
        startAlphaAnimate(mVideoCoverImage);
    }

    @Override
    public void videoStopped() {
        cancelAlphaAnimate(mVideoCoverImage);
        mVideoView.setVisibility(View.INVISIBLE);
        mPlaybackImage.setVisibility(View.VISIBLE);
        mVideoCoverImage.setAlpha(1.f);
        mVideoCoverImage.setVisibility(View.VISIBLE);
    }

  @Override
    public void setActive(View newActiveView, int newActiveViewPosition) {
        videoState = STATE_ACTIVED;
        if (videoLocalPath != null && NetUtil.getNetworkStatus(mContext) == NetUtil.NETWORN_WIFI) {
            mVideoView.setVideoPath(videoLocalPath);
            mVideoView.start();
        }
    }

为什么VideoView设置过不可见之后，即便开始setActive（start之后难道不会调用videoBeginning），也看不到VideoView，依旧看到封面

**Comment by waynell** [comment]
start后会加载视频文件，如果api17以上是视频文件加载完且当准备播放视频第一帧时会调videoBegining，如果是api17以下那就是当视频文件一加载完就会调videoBegining。

你看下你的videoview是不是设置了alpha值，或者在videoBeginning和videoStopped打下log看看
