### ISSUE TITLE
some url is not working 

### ISSUE THREAD

**Issue by monikarora** [waynell/VideoListPlayer#29]
@waynell  Hey  i don't know why but some url  is not working in recycler view(mp4 extension) .
Url upload from iphone device but url extension mp4 .

**Comment by waynell** [comment]
Can you provide a demo project or a video url, i will check it.

**Comment by monikarora** [comment]
@waynell  Hey this url is not working at marshmallow devices( > 6) . http://brightdeveloper.net/gigsValley/assets/images/Event_image/ce1fd1a8fc36eb4f46670fc0ba042a4e.mp4 url work at kitkat devices

**Comment by waynell** [comment]
@monikarora Your video is a MOV(Apple QuickTime) file, the format doesn't supported by Android. Here's [Supported Media Formats](https://developer.android.com/guide/topics/media/media-formats.html) by Android.

**Comment by monikarora** [comment]
@waynell Hey url extension is mp4 ,you can check .I already send url . video is playing in kitkat devices .only not playing in marshallow device.if user send video at sever (IOS) video convert in mp4 extension

**Comment by waynell** [comment]
@monikarora When play this video, MediaPlayer thrown an error (1,-2147483648), it is difficult to locate the problem.

**Comment by monikarora** [comment]
@waynell Okay .thanks for help
