### ISSUE TITLE
如何判断视频是已经下载过了

### ISSUE THREAD

**Issue by shawwinbin** [waynell/VideoListPlayer#4]
怎么通过 glide 判断url 的视频是否下载过了

**Comment by waynell** [comment]
Glide本身没有提供这个API，你可以看看Glide中的SafeKeyGenerator这个类，它是将链接url转成本地缓存文件名，你可以拿到这个文件名去判断这个file是否exist

**Comment by shawwinbin** [comment]
@waynell 谢谢  我试试
