### ISSUE TITLE
NullPointerException onScroll

### ISSUE THREAD

**Issue by hoanghiephui** [waynell/VideoListPlayer#5]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference at com.volokh.danylo.visibility_utils.items.ListItemData.getIndex(ListItemData.java:22) at com.volokh.danylo.visibility_utils.items.ListItemData.getVisibilityPercents(ListItemData.java:42) at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.calculateActiveItem(SingleListViewItemActiveCalculator.java:309) at com.volokh.danylo.visibility_utils.calculator.SingleListViewItemActiveCalculator.onStateTouchScroll(SingleListViewItemActiveCalculator.java:76)

When I am trying to scroll it is giving the NullPointerException.I didn't find any way to setCurrentItem in SingleListViewItemActiveCalculator

**Comment by waynell** [comment]
please update version to 1.1 and try  again
