### ISSUE TITLE
Video not play

### ISSUE THREAD

**Issue by mdtuyen** [waynell/VideoListPlayer#6]
Hi, I use this library load video but after download video not play (only android 4.1.2). This is log:

 E/MediaPlayer: Uri is  <URL suppressed>
 W/QComExtractorFactory: Didn't match the sniff <=== status = 5 
 W/QComExtractorFactory: Not matched with any sniff above, lets try other sniffs 
 W/QComExtractorFactory: Not matched with any sniff above, lets try other sniffs 
 W/QComExtractorFactory: Didn't match the sniff <=== status = 1 
 W/QComExtractorFactory: Didn't match the sniff <=== status = 1 
 W/QComExtractorFactory: Didn't match the sniff <=== status = 1

**Comment by waynell** [comment]
Please tell me which version you are using
