### ISSUE TITLE
视频在没有开始加载的时候 能否获取第一帧占位图

### ISSUE THREAD

**Issue by z8806c** [waynell/VideoListPlayer#8]
视频在没有开始加载的时候 能否获取第一帧占位图

**Comment by waynell** [comment]
获取视频的第一帧需要等待视频文件下载完之后才行，这时用第一帧占位其实意义不大。所以最好的做法用一张图片做视频占位。

**Comment by z8806c** [comment]
想知道 类似  内涵段子 这类APP gif 视频 图文混排的,视频未加载显示的为第一帧

**Comment by waynell** [comment]
内涵段子的视频第一帧是一张webp图片，这张图片就是从视频中截取出来的第一帧。预加载的时候先下载这张图片，然后点击播放按钮后再播放视频。

**Comment by z8806c** [comment]
感谢  思路~~~~·
